# History and log sensors

# Rolling 30-day usage for key entities (drives dashboard insights without massive DB growth)
- platform: history_stats
  name: Floor Lamp On (30d)
  entity_id: light.floor_lamp
  state: "on"
  type: time
  start: "{{ now() - timedelta(days=30) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: TV Light On (30d)
  entity_id: light.tv_light
  state: "on"
  type: time
  start: "{{ now() - timedelta(days=30) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Kitchen Bench On (30d)
  entity_id: light.kitchen_bench
  state: "on"
  type: time
  start: "{{ now() - timedelta(days=30) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Kitchen Strip On (30d)
  entity_id: light.kitchen_strip
  state: "on"
  type: time
  start: "{{ now() - timedelta(days=30) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: Bedroom Light On (30d)
  entity_id: light.bedroom
  state: "on"
  type: time
  start: "{{ now() - timedelta(days=30) }}"
  end: "{{ now() }}"

# Optional: Fan runtime last 30 days (if entity id exists)
#- platform: history_stats
#  name: Purifier On (30d)
#  entity_id: fan.living_room_air_purifier
#  state: "on"
#  type: time
#  start: "{{ now() - timedelta(days=30) }}"
#  end: "{{ now() }}"

# Log tail sensors removed - file platform is deprecated
# Use command_line sensor or logbook instead
# For now, remove these entries to avoid config errors

## Git sync output (on-demand read)
- platform: command_line
  name: Last Git Sync Output
  command: 'bash -c "tail -n 40 /config/.git_sync.log 2>/dev/null || echo \"No git sync log\""'
  scan_interval: 86400   # daily fallback; updated on-demand via homeassistant.update_entity
  value_template: '{{ value | replace("\n"," \\n ") | truncate(1000) }}'
  icon: mdi:history
